### ISSUE TITLE
shebang "#!perl -w"

### ISSUE THREAD

**Issue by sandy-lcq** [perl5-dbi/dbi#109]
Hi, 

Like file dbixs_rev.pl and some other files in this repo, it has shebang "#!perl -w", but seems this shebang cannot work on every system.
I run on linux system:
run "perl ./dbixs_rev.pl":   works well.
run "./dbixs_rev.pl":  report error: "-sh: ./dbixs_rev.pl: cannot execute: required file not found."

But if I change the shebang to "#!/usr/bin/perl -w",  run "./dbixs_rev.pl" works well.  

Should we update the shebang of these files?

**Comment by Tux** [comment]
See d0be81dba913b51ed5f3d3d8d6bc396680e3b116
