### ISSUE TITLE
Uninitialized value $row[0] warning emitted after upgrading from 1.643 to 1.644

### ISSUE THREAD

**Issue by ugexe** [perl5-dbi/dbi#129]
After upgrading from 1.643 to 1.644 I've noticed a new warning occurring
> Use of uninitialized value $row[0] in hash element at /foo/bar/baz/lib/perl5/x86_64-linux/DBI.pm line 2121.

The lines mentioned above:

https://github.com/perl5-dbi/dbi/blob/bd7bdbae4f2387f4c349bb6ec9de9def18e6122c/DBI.pm#L2117-L2121

If `@row` only ever contained `undef` it seems like it should have been emitting this warning in previous versions:

```
$ perl -e 'use warnings; my @row = (undef) x 5; my $x = {}; my $z = $x->{$row[0]}'
Use of uninitialized value $row[0] in hash element at -e line 1.
```

Looking at the change log the only thing that stuck out to me was https://github.com/perl5-dbi/dbi/commit/860c8b80ef391492a38c1c31400cba4371978ebf but it isn't obvious to me *how* moving the `use warnings` in that way would cause this (and so I might be totally wrong).

**Comment by ugexe** [comment]
I think I misunderstood the cause of the warning I was seeing so I'm going to close this

**Comment by LordAro** [comment]
I'm seeing this too (in 1.645), but I don't understand the cause of the warning. What was your solution @ugexe?

**Comment by ugexe** [comment]
I had a query like:
```
SELECT DISTINCT foo AS bar FROM baz;
```
which I updated to:
```
SELECT DISTINCT foo AS bar FROM baz WHERE foo IS NOT NULL;
```

**Comment by Tux** [comment]
@JRaspass any insights?

**Comment by Tux** [comment]
If `$row[$_]` is undefined for whatever reason, it should be skipped completely in that loop.

That code stems from b7509285f806c4e72eb2cde832cab3c18956c5d3 (`2005-03-14`) "Initial commit of enhanced fetchall_hashref"

Thar part effectively changed
``` perl
    my $key_value;
    $sth->bind_col ($index, \$key_value) or return;
    my %rows;
    while (my $row = $sth->fetchrow_hashref ($hash_key_name)) {
        $rows{$key_value} = $row;
        }
    return \%rows;
```
to
``` perl
    $sth->bind_columns (\(@row));
    while ($sth->fetch) {
        my $ref = $rows;
        $ref = $ref->{$row[$_]} ||= {} for @key_indexes;
        @{$ref}{@$NAME} = @row;
        }
    return $rows;
```

**Comment by LordAro** [comment]
You're quite right - I was also effectively doing a  `fetchall_hashref` with a key field that was sometimes NULL. Altering the query and key to use `id` as the key as it should have been and all is well.
