### ISSUE TITLE
Experimental status of `statistics_info`

### ISSUE THREAD

**Issue by dveeden** [perl5-dbi/dbi#134]
The docs say `statistics_info()` is experimental. However it has been labeled as such for a long time. Maybe it is time to remove the experimental label?

https://github.com/perl5-dbi/dbi/blob/87e6c731b464dc862afd1ba95c8b362fcfbee0db/DBI.pm#L5441

https://metacpan.org/pod/DBI#statistics_info

**Comment by Tux** [comment]
Remove "experimental" tag from statistics_info () (issue#134)
af952b35b7d8acd6f306ebcbf82b3bb097c0527d

**Comment by Tux** [comment]
`TABLE_SCHEMA` does not occur anywhere in the code, so I guess that was deliberate. Too late to change that.
