### ISSUE TITLE
dbih_getcom handle DBI::dr=... is not a DBI handle (has no magic) during global destruction

### ISSUE THREAD

**Issue by esabol** [perl5-dbi/dbi#92]
We have an old 32-bit/i686-linux environment that uses Perl 5.8.6. Yeah, I know that's ancient and we should upgrade to a more modern version of Perl. But the system is being retired in less than a year, so we're procrastinating on that task until then. So why bother upgrading DBI? Well, there's that CVE for DBI < 1.643....

Anyway, when I test DBI 1.643 on this 32-bit Perl 5.8.6 system, I get the following:
```
t/02dbidrv.t .................... 1/54 SV = RV(0x9d33674) at 0x9d1e8b8
  REFCNT = 1
  FLAGS = (ROK,READONLY)
  RV = 0x9c8d2c4
        (in cleanup) dbih_getcom handle DBI::dr=HASH(0x9c8d2c4) is not a DBI handle (has no magic) during global destruction.
...
t/zvg_02dbidrv.t ................ 1/54 SV = RV(0x8327c5c) at 0x832588c
  REFCNT = 1
  FLAGS = (ROK,READONLY)
  RV = 0x8282ab4
        (in cleanup) dbih_getcom handle DBI::dr=HASH(0x8282ab4) is not a DBI handle (has no magic) during global destruction.
```
The tests all seemingly pass, but I was wondering if the above is anything we should worry about?

**Comment by timbunce** [comment]
> The tests all seemingly pass, but I was wondering if the above is anything we should worry about?

No. Global destruction is very chaotic and the tests are very pedantic.

I'm sure this would not be a problem.
